[theme]
base = "dark"
primaryColor = "#6e56cf"
backgroundColor = "#111113"
secondaryBackgroundColor = "#18191b"
textColor = "#edeef0"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

