[theme]
base = "dark"
primaryColor = "#7456F7"
backgroundColor = "#070B14"
secondaryBackgroundColor = "#0D1322"
textColor = "#E6EDF3"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
